export const nameBand = 'HIKARU UTADA';
export let nameSongs = [
	"ONE LAST KISS - 3.0",
	"BEAUTIFUL WORLD",
	"ONE LAST KISS - 2.0 ",
	"FIRST LOVE",
	"ONE LAST KISS - PIANO",
	"FLAVOR OF LIFE",
	"PRISONER OF LOVE",
	"PASSION",
	"CAN YOU KEEP A SECRET?",
	"DISTANCE",
	"TRAVELING",
	"SANCTUARY",
	"SIMPLE AND CLEAN",
	"SAKURA DROPS",
	"HEART STATION",
	"ETERNALLY",
	"LETTER",
	"COLORS",
	"KISS & CRY",
	"DAREKA NO NEGAI GA KANAU KORO"
]